version: 2
jobs:
  build:
    working_directory: ~/mern-starter
    # The primary container is an instance of the first list image listed. Your {% comment %} TODO: Job {% endcomment %}build commands run in this container.
    docker:
      - image: circleci/node:8.0.0
    # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.
    #  - image: mongo:3.4.4
    steps:
      - checkout
      # - run:
      #     name: Update npm
      #     command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Deploy to Github Pages
          command: |
            git config --global user.email gt@kainy.cn
            git config --global user.name CircleCI
            #拉取
            mkdir .deploy_git && cd ./.deploy_git/
            git clone "git@github.com:FJUT/vue-element-admin.git"
            cd ./vue-element-admin/
            sed -i'' "s~git@github.com:FJUT/vue-element-admin.git~https://${GH_TOKEN}:x-oauth-basic@github.com/kainy/admin.kainy.cn.git~" ./.git/config
            #cat ./.git/config
            #检出
            git checkout --orphan gh-pages
            #cat ./.git/config
            #pwd
            #ls
            git rm -rf .
            cd ../../
            #打包
            npm run build:sit
            cp ./dist/. .deploy_git/vue-element-admin/ -r
            cd ./.deploy_git/vue-element-admin/
            #发布
            git add .
            git commit -a -m "pages commit"
            git push origin gh-pages --force
  test:
    docker:
      - image: circleci/node:8.0.0
      #- image: mongo:3.4.4
    steps:
      - checkout
      - run:
          name: Test
          command: npm test
      - run:
          name: Generate code coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: my-wafer2