version: 1
machine:
  timezone:
    Asia/Shanghai
  node:
    version: 8.0.0

dependencies:
  override:
    - npm install

deployment:
  production:
    branch: my-wafer2
    commands:
      - git config --global user.name "CircleCI"
      - git config --global user.email "gt@kainy.cn"
      - . deploy.sh